FROM ubuntu:focalLABEL maintainer="Harsh Jalutharia" \
      description="Docker Image for c++ template"
ENV TZ=America/New_York
RUN apt-get update -y && \
    apt-get install -y tzdataRUN apt-get install -y --no-install-recommends\
                    gcc-9 \
                    g++ \
                    clang-10 \
                    build-essential \
                    cmake \
                    unzip \
                    ca-certificates && \
    apt-get autoclean && \
    apt-get autoremove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*